[package]
name = "alan"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam = { version = "0.8.4", features = [] }
serde_json = "1.0.111"
rand = "0.8.5"
